### ISSUE TITLE
Would like to set "setEmitUseStrict" as option

### ISSUE THREAD

**Issue by shirollo** [primefaces-extensions/resources-optimizer-maven-plugin#110]
Could you please support the option of "setEmitUseStrict" with plugin option?

**Comment by melloware** [comment]
Let me look it should be easy to add.

**Comment by shirollo** [comment]
I appreciate it.
I have used JDK8 version so I would be grateful if you add it to 2.4.2 ver as well.

**Comment by melloware** [comment]
Yep I will try and add it to both versions.

**Comment by melloware** [comment]
@shirollo I don't see a `setEmitStrict` property on the Google Closure Compiler?

See docs: https://github.com/google/closure-compiler

**Comment by melloware** [comment]
Found it.

**Comment by melloware** [comment]
2.4.3 deployed to Maven Central with `<emitUseStrict>true</emitUseStrict>` now available.  Let me know how it goes.

**Comment by shirollo** [comment]
@melloware 
I tested that it works.
Thank you for your help!
