### ISSUE TITLE
Css Compressor has a problem with replacing "calc function"

### ISSUE THREAD

**Issue by shirollo** [primefaces-extensions/resources-optimizer-maven-plugin#112]
Hi.

Css Compressor does't return the result that I expected because of CssCompressor line#552.

e.g:
```
.test {
	left: calc(50% - 84px);
}

.test2-test:nth-child(2) {
	display: contents;
}
```

Result:
`.test{left:calc(50% - 84px)}.test2 - test:nth - child(2){display:contents}`

Would you give me some advice to avoid this issue?
Thank you!

**Comment by melloware** [comment]
This might be fixed in a later version I have to backport the fixes to the Java 8

**Comment by melloware** [comment]
OK just ran it through the code in master and here is what it generates.

```css
.test{left:calc(50% - 84px)}.test2 - test:nth - child(2){display:contents}
```

Does that look like what you want?

**Comment by melloware** [comment]
Actually that looks just like yours.  Can you please post your expected output?  I will add a unit test.

**Comment by shirollo** [comment]
I expected like that.

`.test{left:calc(50% - 84px)}.test2-test:nth-child(2){display:contents}`

**Comment by melloware** [comment]
Yep its this regex is the problem: https://regex101.com/r/YLmgL7/1

**Comment by shirollo** [comment]
I supporse you should fix the following regex.

`p = Pattern.compile("calc\\([^;]*\\)");`

Semicolon is already deleted by the following process.

```
// remove unnecessary semicolons
css = css.replaceAll(";+}", "}");
```

**Comment by melloware** [comment]
Can you give me an example. When I just tocuhed that regex multiple tests broke.

**Comment by melloware** [comment]
See this commit.  That fixes this newly added unit test and no other tests fail!

https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/6aaa0d22b2b334b7fff6e054b2852b472a0cb73e

**Comment by melloware** [comment]
Should be in Maven Central if you want to try it.

**Comment by shirollo** [comment]
@melloware 
I finally get new ver.
I tested and it is all good now.
Thank you very much!
