### ISSUE TITLE
The plugin should support the 'skip' plugin parameter

### ISSUE THREAD

**Issue by klaros-testmanagement** [primefaces-extensions/resources-optimizer-maven-plugin#12]
For faster builds it is desirable to skip non-essential maven targets in profiles.

Resource optimization is one of those targets and thus it should be able to control this via a plugin parameter.

I will provide a pull request for this.

**Comment by melloware** [comment]
Awesome much appreciated

**Comment by melloware** [comment]
I updated the WIKI documentation to add the `skip` parameter.

https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Maven-plugin-for-web-resource-optimization

**Comment by stolp** [comment]
Thanks, missed that one. No need to hurry with a release, you should be busy elsewhere :)

**Comment by melloware** [comment]
:) Not a big deal this is easy to do a release of if you need this in Maven Central.  I have updated the Google Closure plugin a couple of times also.    Its been since May since I last released this so I think i will release this today.

**Comment by melloware** [comment]
2.3.5 is now in Maven Central.

**Comment by stolp** [comment]
Crosschecked and enabled. Works great. Thanks!
