### ISSUE TITLE
Support embedding data uris for non-JSF resources

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces-extensions/resources-optimizer-maven-plugin#130]
Support and embed simple relative urls in CSS files like:
```
  background-image: url(../images/remove.svg);
```

Because I want to pack a single JS+CSS library as both webjar for use in JSF UI and as a npm package for use in React UI. So I don't want to hardcode `#{resource['...']}` in the CSS (which also prevents these references from working in a simple openable demo.html including these JS and CSS for development/debugging purposes).

**Comment by melloware** [comment]
Hmmm this should be doable I haven't looked at this code in a long time but it seems doable.

**Comment by melloware** [comment]
It might be a matter of tweaking this regex a little which right now splits the resource URI into paths.

https://regex101.com/r/uzO9hD/1

**Comment by VsevolodGolovanov** [comment]
@melloware, 
```
        // Check if the size of dataURI is limited to 32KB (because IE8 has a 32KB limitation)
        final boolean exceedLimit = dataUri.length() >= SIZE_LIMIT;
        if (exceedLimit) {
            return null;
        }
```
Can I delete this or is this still necessary to rebuild older PFE versions or something? Or at least I could make it an option...
https://caniuse.com/?search=data%20URI

**Comment by melloware** [comment]
Nope delete it as IE is no longer supported!

**Comment by melloware** [comment]
I will make a 2.6.0 release today.

**Comment by melloware** [comment]
2.6.0 is now in Maven Central.
