### ISSUE TITLE
How to optimize CommonJS Modules?

### ISSUE THREAD

**Issue by nolddor** [primefaces-extensions/resources-optimizer-maven-plugin#155]
Hi there, I came across this awesome maven plugin, however while trying to optimize my *.JS files with `failOnWarning` enabled I see the following as output:
```
[ERROR] JSC_UNDEFINED_VARIABLE. variable define is undeclared at /home/nolddor/git/mvn-test/target/classes/js/TestCommon.js line 6 : 4
[ERROR] JSC_UNDEFINED_VARIABLE. variable require is undeclared at /home/nolddor/git/mvn-test/target/classes/js/TestCommon.js line 21 : 0
```
It looks like i need to explicity enable CommonJS module support by using `--process_common_js_modules` flag / **[CompilerOptions#setProcessCommonJSModules](https://javadoc.io/static/com.google.javascript/closure-compiler/v20190301/com/google/javascript/jscomp/CompilerOptions.html#setProcessCommonJSModules-boolean-)**, but i do not see the option on this maven plugin. 

Refers to [google/closure-compiler/wiki/JS-Modules#commonjs-modules](https://github.com/google/closure-compiler/wiki/JS-Modules#commonjs-modules) section.

### Plugin Config
```
            <plugin>
                <groupId>org.primefaces.extensions</groupId>
                <artifactId>resources-optimizer-maven-plugin</artifactId>
                <version>2.6.1</version>
                <executions>
                    <execution>
                        <id>optimize</id>
                        <goals>
                            <goal>optimize</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <warningLevel>VERBOSE</warningLevel>
                    <failOnWarning>true</failOnWarning>
                    <languageIn>ECMASCRIPT_2015</languageIn>
                    <inputDir>${project.build.directory}/classes/js</inputDir>
                    <includes>
                        <include>**/*.js</include>
                    </includes>
                </configuration>
            </plugin>
```

**Comment by nolddor** [comment]
Hi @melloware let me know if i missed something on your docs, thanks!

**Comment by melloware** [comment]
Nope it looks like I need to add this option for the Google Closure Compiler.  I will add it.

**Comment by melloware** [comment]
Added new flag

```xml
<processCommonJSModules>true</processCommonJSModules>
```

2.6.2 SHould be in Maven Central in the new couple of hours

**Comment by nolddor** [comment]
Thanks for the quick fix!

**Comment by melloware** [comment]
@nolddor let me know if it fixes your issue

**Comment by nolddor** [comment]
It does.

**Comment by melloware** [comment]
Awesome!  Happy to help and thanks for the report.
