### ISSUE TITLE
CSS: incorrectly applies and removes spaces to variables and calc functions

### ISSUE THREAD

**Issue by Jimmy12384** [primefaces-extensions/resources-optimizer-maven-plugin#168]
original: `margin: 0 calc(var(--month-margin) / 2) var(--month-margin) 0;`
bugged: `margin: 0 calc(var(--month - margin) / 2)var(--month - margin) 0;`

original: `min-height: calc((var(--duration) * (var(--month-height) + var(--month-margin)) - var(--month-margin)));`
bugged: `min-height: calc((var(--duration) * (var(--month - height) + var(--month - margin)) - var(--month - margin)));`
^^ also does it for max-height

original: `top: calc(var(--month-offset) * (var(--month-height) + var(--month-margin)));`
bugged: `top: calc(var(--month - offset) * (var(--month - height) + var(--month - margin)));`

original: `width: calc(100% - 2 * var(--current-date-border));`
bugged: `width: calc(100% - 2 * var(--current-date - border));`

it looks like it has a tendency to add spaces to variable names with dashes. At first I was wondering if I was just naming them weird but using dashes seems to be the standard for css variables, it also removed the space between calc() and var() in the first one.

**Comment by melloware** [comment]
I juts pushed a failing unit test: https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/d0e71cf71315cac272591c4b38b7b8982b42a6fe

**Comment by melloware** [comment]
@Jimmy12384 feel free to improve on this gem: https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/388c7dce224cf2e3388e564b1a292853b089cf9e

**Comment by Jimmy12384** [comment]
Looks good to me, thanks @melloware!

**Comment by melloware** [comment]
I will cut a 2.6.3 release tomorrow.

**Comment by melloware** [comment]
OK right now we have this test:

https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/test/resources/bug168.css

With this after compression assert:

https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/test/resources/bug168.css.min

**Comment by melloware** [comment]
@Tsyklop please open a new ticket as this is likely a different scenario

**Comment by melloware** [comment]
if I write a test i see it compresses to this...

```css
.info{margin:calc(var(--spacing-3xl) * -1)calc(var(--spacing-2xl) * -1)0calc(var(--spacing-2xl) * -1)}
```

**Comment by melloware** [comment]
OK please open a new ticket so we can track this.
