### ISSUE TITLE
Aggregation does not behave correctly when input files end with a comment

### ISSUE THREAD

**Issue by jbb01** [primefaces-extensions/resources-optimizer-maven-plugin#211]
When using an aggregation, the input files are concatenated with a semicolon separating them. While this works in most cases, it fails when an input file ends with a comment (like a source map url). In this case, the first line of the next input file will also be commented out which can result in compilation failures.

### reproducer

1-file.js
```js
//# sourceMappingURL=1-file.js.map;
```

2-file.js
```js
/*
 * Hello World!
 */
```

aggregation.source.js
```js
//# sourceMappingURL=1-file.js.map;;/*
 * Hello World!
 */
```

Error message
```
Resources optimization failure: Illegal char <*> at index 16: 1-file.js.map;;/*
```

[reproducer.zip](https://github.com/user-attachments/files/17202571/reproducer.zip)

**Comment by blutorange** [comment]
It happens here in [AbstractOptimizer](https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/AbstractOptimizer.java#L96). You probably need to make the delimiter dependent on the type of file, i.e. JS files require `\n;`, CSS files just `\n`.

**Comment by melloware** [comment]
@blutorange yep but his looks like its 2 JS files bu the last one is a sourcemapping comment the semicolon is breaking it?

**Comment by melloware** [comment]
Oh no i see its the line wrap is needed `/n`

**Comment by melloware** [comment]
PR submitted

**Comment by melloware** [comment]
2.6.5 should be in Maven Central soon with this fix

**Comment by jbb01** [comment]
Thanks for the quick resolution. I'm honestly impressed how fast you guys are.

**Comment by melloware** [comment]
Thanks for the bug report!
