### ISSUE TITLE
Restore JDK8 Functionality

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#73]
Google Closure Compiler as of 06/2022 requires JDK11 now: https://github.com/google/closure-compiler/issues/3956

Going to revert to `v20220502` So I can cut one last JDK8 compatible release

**Comment by miroskow** [comment]
I will stay at 2.3.9 ;)

**Comment by melloware** [comment]
HA yeah I am releasing 2.4.0 its just bumping the Google Closure back 1 version to last month.   The Plugin 2.5.0+ will be JDK11 only from then on!
