### ISSUE TITLE
CSS Compressor: Issue compressing complex calcs

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#75]
original Issue: https://github.com/yui/yuicompressor/issues/330

Raw:
```css
right: calc(((100% - 1200px) / 2) + 16px);
```

Incorrectly compressed to:
```css
right: calc(((100% - 1200px) / 2)+16px);
```

No space in the `+16px`

**Comment by melloware** [comment]
OK because java REGEX doesn't support balancing groups or recursion this is almost impossible to do with the current REGEXES. It would need to use real parsing to find matching parens.

**Comment by melloware** [comment]
Here is a Regex 101. showing the current issue: https://regex101.com/r/N2rr2m/1

**Comment by jepsar** [comment]
Not bulletproof, but what about `calc\([^;]+;` (untested.. I'm on my phone)

**Comment by melloware** [comment]
OK this one seems to work after testing yours `calc\([^;]*\)` and tweaking!  All unit tests passing.
