### ISSUE TITLE
CSS Compressor: Keep 0 units in linear-gradient

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#80]
Original issue: https://github.com/yui/yuicompressor/issues/295

https://www.w3schools.com/css/css3_gradients.asp
Using Angles
If you want more control over the direction of the gradient, you can define an angle, instead of the predefined directions (to bottom, to top, to right, to left, to bottom right, etc.).
Syntax
`background: linear-gradient(angle, color-stop1, color-stop2);`
Before
`linear-gradient(0deg, #eee 0px, #eee 10px, transparent 10px, transparent 50px, #eee 50px),`
After
`linear-gradient(0, #eee 0px, #eee 10px, transparent 10px, transparent 50px, #eee 50px),`

**Comment by miroskow** [comment]
When will version 2.5.0 be released? :)

**Comment by melloware** [comment]
I can release it now if you want?

**Comment by melloware** [comment]
OK 2.5.0 is in maven central now with latest Google Closure + a bunch of CSS fixes
