### ISSUE TITLE
CSS : Whitespaces removed around operator of calc() function

### ISSUE THREAD

**Issue by brivalin** [primefaces-extensions/resources-optimizer-maven-plugin#84]
I'm facing a problem when optimizing CSS files containing the CSS function calc(), whitespaces inside this function are removed.

This problem only appear from 2.5.0 version. Previous versions didn't remove these whitespaces.

To be interpreted by browsers, the calc() function must have whitespaces around operator '-' or '+'. 
Then, the expected behavior should be to not remove whitespaces for calc() function.

To reproduce the problem, you can use this CSS code and optimize it with plugin :
`height: calc(100vh - 20px);`

You should get this : 
`height: calc(100vh-20px);`

**Comment by melloware** [comment]
See: https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/issues/75

**Comment by melloware** [comment]
So you are saying

`height: calc(100vh - 20px);`

Should stay

`height: calc(100vh - 20px);` ?

**Comment by melloware** [comment]
Hmm can you also look at the unit test in the commit? 

https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/f95ee29a27c0bb55dceb3f3a816dc9301f7150df

**Comment by brivalin** [comment]
> So you are saying
> 
> `height: calc(100vh - 20px);`
> 
> Should stay
> 
> `height: calc(100vh - 20px);` ?

Yes, Chrome says that : 
`calc(100vh - 20px)` is valid
but all
`calc(100vh -20px)` is invalid
`calc(100vh- 20px)` is invalid
`calc(100vh-20px)` is invalid

**Comment by melloware** [comment]
let me update the unit test

**Comment by melloware** [comment]
Good catch!  It was missing `vh` see my commit and updated unit test. https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/a5de5c485b7edfbe4bfe9a66ad31c9f14074927a

**Comment by brivalin** [comment]
Thank you for the correction 👍 
But from this correction I don't understand why It worked in 2.4.1 version and not 2.5.x ?

**Comment by melloware** [comment]
I think its because of https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/issues/75 that I fixed actually made this issue exposed.  Before 75 the code must have handled this scenario but not the other one.  Very interesting. I will release 2.5.2 tomorrow!

**Comment by melloware** [comment]
2.5.2 is in Maven Central if you want to give it a try.

**Comment by brivalin** [comment]
I updated to 2.5.2 and it works as expected. 
Thank you ! :slightly_smiling_face:

**Comment by melloware** [comment]
Thanks for reporting it and testing it!
